app/__init__.py
"""Initialize web application"""
import os.path
from tests.log import logger, set_log
from flask_sqlalchemy import SQLAlchemy
from flask import Flask, render_template
from config import config
from flask_bootstrap import Bootstrap
from flask_pagedown import PageDown
from flask_login import LoginManager

PAGEDOWN = PageDown()
LOGIN_MANAGER = LoginManager()
LOGIN_MANAGER.session_protection = 'strong'
LOGIN_MANAGER.login_view = 'login'   # Where register login router

def create_app(config_name):
    """Instantiate Flask app
    Including database, blueprints and etc.
    """
    logger.info(__name__ + "  " + config[config_name].SQLALCHEMY_DATABASE_URI)
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    Bootstrap(app)
    PAGEDOWN.init_app(app)
    LOGIN_MANAGER.init_app(app)

    # Initialize database and ORM.
    # If tables are not exist yet, create a new one.
    from app.alchemy_model import DB
    #with app.app_context():
    logger.info(__name__ + "test DB")
    DB.init_app(app)
    if not os.path.isfile(config[config_name].DB_PATH):
        open(config[config_name].DB_PATH, 'w+')
        DB.drop_all(app=app)
        DB.create_all(app=app)
    # Register all blueprints to app
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    # from .api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)
    # app.register_blueprint(api_1_0_blueprint)

    app.jinja_env.add_extension('jinja2.ext.do')
    return app

app/api_1_0/__init__.py
''' Initialize blueprint of api '''
from flask import Blueprint

api = Blueprint('api', __name__)

from . import authetication, comments, decorators, errors, posts, users

app/main/__init__.py
"""initialize Blueprint main"""
from tests.log import logger, set_log
from flask import Blueprint

main = Blueprint('main', __name__, template_folder='./templates', static_folder='../static')
logger.info("initialize Blueprint 'main', root_path is:" + main.root_path)
from .import views, errors

app/main/views.py
"""Routers and views for blueprint 'main'
"""
from tests.log import logger, set_log
from flask_login import login_required, current_user
from app.alchemy_model import Post
from app.form import PostForm
from flask import (request, render_template, session, url_for, redirect, flash)
from .import main

@main.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    """depends on method
    GET  direct to where writing new post
    POST process new post submit
    """
    post_form = PostForm()
    if post_form.validate_on_submit():
        post = Post.insert(title=post_form.title.data,
                           content=post_form.content.data,
                           published=post_form.published.data,
                           author=current_user._get_current_object()
                          )
        flash('Post created successfully.', 'success')
        if post.published:
            return redirect(url_for('main.detail', id=post.id))
        else:
            return redirect(url_for('main.edit', id=post.id))
    return render_template('create.html', post_form=PostForm())

@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    ''' Edit dedicated post '''
    post = Post.query.filter_by(id=id).first_or_404()
    post_form = PostForm()
    #check if method is 'POST' & data is validate
    if post_form.validate_on_submit():
        post.modify(post_form.title.data,
                    post_form.content.data,
                    post_form.published.data
                   )
        flash('Post saved successfully.', 'success')
        if post.published:
            return redirect(url_for('.detail', id=post.id))
        else:
            return redirect(url_for('.edit', id=post.id))
    #flash('Title and Content are required.', 'danger')

    #get data from DB to form
    post_form.title.data = post.title
    post_form.content.data = post.content
    post_form.published.data = post.published
    return render_template('edit.html', post_form=post_form)

@main.route("/posts/<int:id>/")
def detail(id):
    ''' Get dedicated post '''
    if current_user.is_authenticated:
        post = Post.query.filter_by(id=id).first_or_404()
    # If not logged yet, only published post allowed
    else:
        post = Post.query.filter_by(id=id, published=True).first_or_404()
    return render_template('detail.html', post=post, page_id=id)

@main.route('/')
def index(page=1):
    """Direct to homepage.
    check whether the browser has logged in
    If loggin in: editing posts is allowed
    If not: it can only read posts

    Support search in future
    """

    #posts is a class Pagination object
    page = request.args.get('page', 1, type=int)
    pagination = Post.query_posts(page)
    posts = pagination.items
    return render_template("index.html",
                           posts=posts,
                           pagination=pagination
                          )

app/main/templates/base.html
<!doctype html>
<html>
  <head>
    <title>Blog</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex">
    <link rel=stylesheet type=text/css href="{{ url_for('main.static', filename='css/blog.min.css') }}" />
    <link rel=stylesheet type=text/css href="{{ url_for('main.static', filename='css/hilite.css') }}" />
    {% block extra_head %}{% endblock %}
    <script src="{{ url_for('main.static', filename='js/jquery-1.11.0.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('main.static', filename='js/bootstrap.min.js') }}"></script>
    {% block extra_scripts %}{% endblock %}
  </head>

  <body>
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('main.index') }}">Blog</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% if current_user.is_authenticated%}
              <li><a href="{{ url_for('main.create') }}">创建新博客</a></li>
              <li><a href="{{ url_for('auth.logout') }}">登出</a></li>
            {% else%}
              <li><a href="{{ url_for('auth.login')}}">登入</a></li>
              <li><a href="{{ url_for('auth.register')}}">注册</a></li>
            {% endif %}
            {% block extra_header %}{% endblock %}
          </ul>
          {% block search_bar %}
            <form action="{{ url_for('main.index') }}" class="navbar-form navbar-right" id="search-form" method="get" role="search">
              <div class="form-group">
                <input class="form-control" name="q" placeholder="Search" type="text" value="{% if search %}{{ search }}{% endif %}">
              </div>
            </form>
          {% endblock %}
        </div>
      </div>
    </div>

    <div class="container">
      {% for category, message in get_flashed_messages(with_categories=true) %}
        <div class="alert alert-{{ category }} alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <p>{{ message }}</p>
        </div>
      {% endfor %}

      {% block page_header %}
        <div class="page-header">
          <h1>{% block content_title %}{% endblock %}</h1>
        </div>
      {% endblock %}

      {% block content %}{% endblock %}

      <footer>
        <hr />
        <p>Blog, &copy; 2017</p>
      </footer>
    </div>
  </body>
</html>

app/main/templates/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf%}
{% block extra_scripts %}
    <!-- achieve markdown preview -->
    {{pagedown.include_pagedown()}}
{% endblock %}

{% block title %}Create post{% endblock %}

{% block content_title %}创建新博客{% endblock %}

{% block content %}
{{wtf.quick_form(post_form)}}

{% endblock %}

app/main/templates/detail.html
{% extends "base.html" %}

{% block extra_scripts %}
    {{pagedown.include_pagedown()}}
{% endblock %}

{% block title %}{{ post.title }}{% endblock %}

{% block content_title %}{{ post.title }}{% endblock %}

{% block extra_header %}
{% endblock %}

{% block content %}

<div class="post-toolbar">
  {% if current_user == post.author%}
    <a class="btn btn-primary" href="{{url_for('main.edit', id=page_id)}}" role="button">编辑</a>
  {% endif %}
</div>
<p>{{post.author.username}} 创建于 {{ post.timestamp.strftime('%Y/%m/%d   %X') }}</p>
  {% if post.content_html %} 
    {{ post.content_html | safe }}
  {% else %}
    {{ post.content}}
  {% endif %}
{% endblock %}

app/main/templates/edit.html
{% extends "create.html" %}

{% block title %}Edit post{% endblock %}

{% block content_title %}编辑博客{% endblock %}

{% block form_action %}{{ url_for('main.edit', id = post.id) }}{% endblock %}

{% block save_button %}Save changes{% endblock %}

app/main/templates/includes/_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}{{ fragment }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{{ fragment }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

app/main/templates/includes/pagination.html
{% if pagination.get_page_count() > 1 %}
<ul class="pager">
  {% if pagination.get_page() > 1 %}
    <li class="previous"><a href="./?{{ request.args|clean_querystring('page', page=pagination.get_page() - 1) }}">&laquo; Previous {{ pagination.get_page() - 1 }} / {{ pagination.get_page_count() }}</a></li>
  {% else %}
    <li class="previous disabled"><a href="#">&laquo; Previous</a></li>
  {% endif %}
  {% if pagination.get_page_count() > pagination.get_page() %}
    <li class="next"><a href="./?{{ request.args|clean_querystring('page', page=pagination.get_page() + 1) }}">Next {{ pagination.get_page() + 1 }} / {{ pagination.get_page_count() }} &raquo;</a></li>
  {% else %}
    <li class="next disabled"><a href="#">Next &raquo;</a></li>
  {% endif %}
</ul>
{% endif %}

app/main/templates/index.html
{% extends "base.html" %}
{% import "includes/_macros.html" as macros %}
{% block title %}Blog entries{% endblock %}
{% block content_title %}{% if search %}Search "{{ search }}"{% else %}Blog entries{% endif %}{% endblock %}

{% block content %}
  <h2>嗨, 
    {% if current_user.is_authenticated %}
    {{ current_user.username }}
    {% else %}
    陌生人
    {% endif %}
    !
  </h2>  
  {% for post in posts%}
    <h3>
      <a href="{% if post.published %}{{ url_for('main.detail', id=post.id)
          }}{% else %}{{ url_for('main.edit', id=post.id) }}{% endif %}">
        {{ post.title }}
      </a>
    </h3>
    <p>创建于 {{ post.timestamp.strftime('%Y/%m/%d   %X') }}</p>
  {% else %}
    <p>现在还没有被创建的博客。</p>
  {% endfor %}
 
  <div class="pagination">
    {{ macros.pagination_widget(pagination, '.index') }}
  </div>
  {% endblock %}

app/main/templates/user.html
<h1>hello {{name}} </h1>